### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by adam2w2** [WKS-uwu/DUCK#2]
Hi can you please Help me i didn't find a script to download drm videos from from https://shahid.mbc.net/ar/

thank you

**Comment by adam2w2** [comment]
[](url)

**Comment by WKS-uwu** [comment]
I don't need to make another justsu for this, I had already done it a long time ago when Duck Naruto still lived in the village before going to train with some frogs, it is not very difficult to get keys from there, I will leave you a L3 as a gift, I hope it will help you.
 -sasuke_duck

https://cdn.discordapp.com/attachments/707710449398841506/916488235780288592/device_client_id_blob
https://cdn.discordapp.com/attachments/707710449398841506/916488236052926534/device_private_key


![image](https://cdn.discordapp.com/attachments/707710449398841506/916443550353338398/da5cd36c5be1caf08736996c18638d10950a7556v2_00.png)

**Comment by adam2w2** [comment]
Hi thanks for reply i know how to do it manually as you explained in https://github.com/WKS-uwu/WKS-KEY
but i want a scrpit to download auto by just adding id like Netflix-videos-downloader.

**Comment by WKS-uwu** [comment]
With a little training you can beat the stupid DRM guys and be envious of the one who shared the Netflix script because he only shared it because he didn't know how to use it and waited for someone to explain how it works, but you like my student with a little L3 power you can make your own script.
 -sasuke_duck

![image](https://cdn.discordapp.com/attachments/707710449398841506/916443550353338398/da5cd36c5be1caf08736996c18638d10950a7556v2_00.png)

**Comment by adam2w2** [comment]
ok thanks

**Comment by hasmevask** [comment]
> Hi can you please Help me i didn't find a script to download drm videos from
> 
> thank you

from which /what web?
